-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_USER';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_USER';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_USER_STATUS';
ALTER TYPE "AuditAction" ADD VALUE 'RESET_USER_PASSWORD';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_SITE';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_SITE';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_SITE';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_INTERVENTION';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_INTERVENTION';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_INTERVENTION_STATUS';
ALTER TYPE "AuditAction" ADD VALUE 'CANCEL_INTERVENTION';
ALTER TYPE "AuditAction" ADD VALUE 'DUPLICATE_INTERVENTION';
